---
- name: Install Packer for RedHat
  when: ansible_os_family == 'RedHat'
  block:
    - name: Install dnf-plugins-core
      become: true
      ansible.builtin.package:
        name: dnf-plugins-core

    - name: Add HashiCorp repository to dnf config manager
      become: true
      ansible.builtin.yum_repository:
        name: hashicorp
        description: HashiCorp Stable Repository
        baseurl: https://rpm.releases.hashicorp.com/fedora/{{ ansible_distribution_major_version }}/x86_64/stable/
        gpgcheck: true
        gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install Packer for Debian
  when: ansible_os_family == 'Debian'
  block:
    - name: Add Hashicorp GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Hashicorp apt repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present

- name: Install Packer package
  become: true
  ansible.builtin.package:
    name: packer
    state: present
...
