---
- name: Init packer
  ansible.builtin.command:
    cmd: packer init .
  args:
    chdir: "{{ packer_working_dir }}"
  changed_when: true

- name: Run packer build
  ansible.builtin.command:
    cmd: packer build -force packer.pkr.hcl
  environment:
    PACKER_LOG: "1"
    PACKER_LOG_PATH: "{{ packer_working_dir }}/packer.log"
  args:
    chdir: "{{ packer_working_dir }}"
  changed_when: true
...
