---
- name: Include task prepare
  ansible.builtin.include_tasks:
    file: prepare.yml

- name: Include task install
  ansible.builtin.include_tasks:
    file: install.yml

- name: Include task build
  ansible.builtin.include_tasks:
    file: build.yml
...