---
- name: Include task prepare
  ansible.builtin.include_tasks:
    file: prepare.yml
    apply:
      tags: prepare

- name: Include task install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: install

- name: Include task build
  ansible.builtin.include_tasks:
    file: build.yml
    apply:
      tags: build
...