---
- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-pip
    - novnc

- name: Install ansible
  ansible.builtin.pip:
    name: ansible

- name: Create novnc service
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/novnc.service
    mode: '0644'
    content: |
      [Unit]
      Description=noVNC Websocket Proxy Service
      After=network.target

      [Service]
      Type=simple
      User=root
      ExecStart=/usr/bin/novnc_proxy --vnc localhost:5900
      Restart=on-failure
      Environment="DISPLAY=:0"
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

- name: Start novnc service
  become: true
  ansible.builtin.service:
    name: novnc
    state: started

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item.path | dirname }}"
    state: directory
    mode: '0775'
  loop: "{{ packer_config_files }}"
  loop_control:
    label: "{{ item.path | dirname }}"

- name: Create required files
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    content: "{{ item.content }}"
    mode: '0644'
  loop: "{{ packer_config_files }}"
  loop_control:
    label: "{{ item.path }}"
...
